name: Docker Image CI

on:
  pull_request:
    branches: [ "release" ]

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    name: CodeQL Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - 
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"
